name: 'Setup Ruby'
description: 'Set up a specific version of Ruby and add the command-line tools to the PATH'
author: 'GitHub'
inputs: 
  ruby-version:
    description: 'Version range or exact version of a Ruby version to use.'
    default: '>= 2.4'
  gem-key:
    description: 'Identifier passed to gem for push via the --key config. Default is rubygems_api_key'
    default: rubygems_api_key
  registry-url:
    description: 'URL for authenticated RubyGems services. rubygems.org does not require this configuration.'
  username:
    description: 'Username to authenticate to registry-url with. Often github.actor is best here.'
  password:
    description: 'Password to authenticate to registry-url with. Often github.token is best here.'
    # Deprecated option, do not use. Will not be supported after October 1, 2019
  version:
    description: 'Deprecated. Use ruby-version instead. Will not be supported after October 1, 2019'
    deprecationMessage: 'The version property will not be supported after October 1, 2019. Use ruby-version instead'
runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist/cleanup/index.js'
